global using Xunit;
global using Microsoft.EntityFrameworkCore;
global using Models.Entities;
global using Aqua_Sharp_Backend.Contexts;
global using Aqua_Sharp_Backend.Services;
global using Aqua_Sharp_Backend.Interfaces;
global using Aqua_Sharp_Backend.Profiles;
global using Models.ViewModels.Device;
global using Microsoft.AspNetCore.Mvc;